CREATE TABLE cms_pages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255),
    seo_name VARCHAR(255),
    short_description VARCHAR(255),
    long_description TEXT
);

INSERT INTO cms_pages(title,seo_name,short_description,long_description) VALUES('Contactos','contactos','Contactos - Lorem ipsum dolor sit amet','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',1,'title','Contactos');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',1,'seo_name','contactos');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',1,'short_description','Contactos - Lorem ipsum dolor sit amet');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',1,'long_description','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',1,'title','Contact Us');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',1,'seo_name','contact-us');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',1,'short_description','Contact Us - Lorem ipsum dolor sit amet');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',1,'long_description','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');


INSERT INTO cms_pages(title,seo_name,short_description,long_description) VALUES('Sobre Nós','sobre-nos','Sobre Nós - Lorem ipsum dolor sit amet','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',2,'title','Sobre Nós');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',2,'seo_name','sobre-nos');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',2,'short_description','Sobre Nós - Lorem ipsum dolor sit amet');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',2,'long_description','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',2,'title','About Us');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',2,'seo_name','about-us');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',2,'short_description','About Us - Lorem ipsum dolor sit amet');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',2,'long_description','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');


INSERT INTO cms_pages(title,seo_name,short_description,long_description) VALUES('FAQ','faq','FAQ - Lorem ipsum dolor sit amet','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',3,'title','FAQ');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',3,'seo_name','faq');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',3,'short_description','FAQ - Lorem ipsum dolor sit amet');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',3,'long_description','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',3,'title','FAQ');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',3,'seo_name','faq');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',3,'short_description','FAQ - Lorem ipsum dolor sit amet');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',3,'long_description','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');



INSERT INTO cms_pages(title,seo_name,short_description,long_description) VALUES('Termos e Condições','termos-e-condicoes','Termos e Condições - Lorem ipsum dolor sit amet','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',4,'title','Termos e Condições');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',4,'seo_name','termos-e-condicoes');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',4,'short_description','Termos e Condições - Lorem ipsum dolor sit amet');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('pt','cms_pages',4,'long_description','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',4,'title','Terms and Conditions');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',4,'seo_name','terms-and-conditions');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',4,'short_description','Terms and Conditions - Lorem ipsum dolor sit amet');
INSERT INTO translations(locale,entity_type,entity_id,field,translation) VALUES('en','cms_pages',4,'long_description','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
